### ISSUE TITLE
求助 vrwkv6.py：RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by jiajia131** [OpenGVLab/Vision-RWKV#20]
if __name__ == "__main__":
    # 初始化模型和输入
    n_embd = 256
    n_head = 4
    n_layer = 6
    layer_id = 1
    key_norm = True
    B = 8
    H = 488
    W = 1
    patch_resolution = (H, W)  # 分辨率，应为 (H, W)
    model = VRWKV_SpatialMix_V6(n_embd, n_head, n_layer, layer_id, key_norm=key_norm).cuda()
    input_tensor = torch.randn(B, H*W, n_embd).cuda()  # 示例输入

    # 前向传播
    output = model(input_tensor, patch_resolution)
    print("Output shape:", output.shape)

    # 模拟目标数据
    target = torch.randn(B, H*W, n_embd).cuda()  # 假设目标数据形状与输出形状相同

    # 定义损失函数和计算损失
    criterion = nn.MSELoss()
    loss = criterion(output, target)
    print("Loss:", loss.item())

    # 反向传播
    loss.backward()

    # 输出一些参数的梯度，以确保反向传播正常工作
    print("Gradient of the first parameter:", next(model.parameters()).grad)

(base) root@I19f66ba2b200801626:/hy-tmp/caogao/Vision-RWKV-master/classification/mmcls_custom/models/backbones# python vrwkv6.py
/usr/local/miniconda3/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Using /root/.cache/torch_extensions/py38_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu118/wkv6/build.ninja...
Building extension module wkv6...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF wkv6_op.o.d -DTORCH_EXTENSION_NAME=wkv6 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/miniconda3/lib/python3.8/site-packages/torch/include -isystem /usr/local/miniconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/miniconda3/lib/python3.8/site-packages/torch/include/TH -isystem /usr/local/miniconda3/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/local/miniconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -c /hy-tmp/caogao/Vision-RWKV-master/classification/mmcls_custom/models/backbones/cuda_v6/wkv6_op.cpp -o wkv6_op.o 
[2/2] c++ wkv6_op.o wkv6_cuda.cuda.o -shared -L/usr/local/miniconda3/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o wkv6.so
Loading extension module wkv6...
Output shape: torch.Size([8, 488, 256])
Loss: 1.018182635307312
Traceback (most recent call last):
  File "vrwkv6.py", line 509, in <module>
    loss.backward()
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "vrwkv6.py", line 69, in backward
    gu = torch.sum(gu, 0).view(H, C//H)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

我在vrwkv6.py里运行以上代码，想验证反向传播。结果在数据长度也就是H *W达到几百时，就会报错。请问是什么原因，无法应用在大分辨率？我在原版的rwkv6里测试没有这个问题。感谢解答

**Comment by EquationWalker** [comment]
自己做backward的测试没报错，分布式一跑就报这个错误，TMAX怎么调都不行，请问如何解决？

**Comment by duanduanduanyuchen** [comment]
> 自己做backward的测试没报错，分布式一跑就报这个错误，TMAX怎么调都不行，请问如何解决？

试试缩小batch size呢？有的时候out of memory也会报这个错

**Comment by jiajia131** [comment]
> 自己做backward的测试没报错，分布式一跑就报这个错误，TMAX怎么调都不行，请问如何解决？

如果你是在自己的网络上

> 自己做backward的测试没报错，分布式一跑就报这个错误，TMAX怎么调都不行，请问如何解决？

你是加入到自己的网络里跑的话，可以在 ‘wkv6_op.cpp’ 里试试注释掉。

// TORCH_LIBRARY(wkv6, m) {      //  移除 TORCH_LIBRARY 的注册，因为它主要用于在 C++ 代码中注册自定义的 PyTorch 操作，并不适用于通过 Python 直接调用的情况
//     m.def("forward", forward);
//     m.def("backward", backward);
// }

**Comment by thucz** [comment]
我遇到了同样的问题，输入是640x320的图像，我把T_MAX调到1600，把这段代码注释掉了，都不太行
// TORCH_LIBRARY(wkv6, m) { // 移除 TORCH_LIBRARY 的注册，因为它主要用于在 C++ 代码中注册自定义的 PyTorch 操作，并不适用于通过 Python 直接调用的情况
// m.def("forward", forward);
// m.def("backward", backward);
// }

**Comment by thucz** [comment]
> 我遇到了同样的问题，输入是640x320的图像，我把T_MAX调到1600，把这段代码注释掉了，都不太行 // TORCH_LIBRARY(wkv6, m) { // 移除 TORCH_LIBRARY 的注册，因为它主要用于在 C++ 代码中注册自定义的 PyTorch 操作，并不适用于通过 Python 直接调用的情况 // m.def("forward", forward); // m.def("backward", backward); // }

我这个看上去是数组越界了，目前网络应该是必须接收方形的图像输入。我换成512x512，就提示OOM error
