### ISSUE TITLE
Cuda not available error when runnng setup.py

### ISSUE THREAD

**Issue by henryzhao0615** [OpenGVLab/Vision-RWKV#35]
Hi,
I am trying to follow segmentation task. And I run sh ./make.sh on my GPU and it said that "Cuda is not available". However, I have cuda in my machine.
Here is the error:
(vrwkv)@vision3d2:~/research/Vision-RWKV/detection/ops$ sh ./make.sh
/home/users/u123/miniconda3/envs/vrwkv/lib/python3.10/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/home/users/u123/research/Vision-RWKV/detection/ops/setup.py", line 70, in <module>
    ext_modules=get_extensions(),
  File "/home/users/u123/research/Vision-RWKV/detection/ops/setup.py", line 43, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel

But if I run "pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118" to install cuda. It said Requirement already satisfied.

I hope you can help me fix this issue. Thanks in advance!

**Comment by henryzhao0615** [comment]
Additionally, I found that for most of machines is not able to run "pip install torch==1.12.1+cu113 torchvision==0.12.0+cu113  -f https://download.pytorch.org/whl/torch_stable.html
" according to the instructions, it will have error. And for mmcv-full, I tried "mim install mmcv-full==2.1.0" to solve. I tried these on two machines, one has a cuda version of 12.4 and one has 11.7. Both show the same result.

**Comment by henryzhao0615** [comment]
for the latest pytorch, mmcv-full 1.7 can not be installed.
