### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by CodeStarting-design** [OpenGVLab/Vision-RWKV#49]
你好，在将代码迁移到下游任务时出现了反向传播报错的问题，请问要如何解决
```bash
Traceback (most recent call last):
  File "train.py", line 218, in <module>
    train(net, loader_train, loader_test, optimizer, criterion)
  File "train.py", line 70, in train
    loss.backward()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issu
```

**Comment by duanduanduanyuchen** [comment]
> 你好，在将代码迁移到下游任务时出现了反向传播报错的问题，请问要如何解决
> 
> Traceback (most recent call last):
>   File "train.py", line 218, in <module>
>     train(net, loader_train, loader_test, optimizer, criterion)
>   File "train.py", line 70, in train
>     loss.backward()
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
>     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
> You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issu

从这上面看不出来具体的问题，还有更详细的信息嘛？
